### ISSUE TITLE
Error format 

### ISSUE THREAD

**Issue by egregors** [logux/django#10]
Is it all error types logux server will expect?
```
["unknownChannel", "1560954022858 38:Y7bysd:O0ETfc 0"] – backend got wrong channel id
["unknownAction", "1560954022858 38:Y7bysd:O0ETfc 1"] – backend got wrong action type 
["error", "PostgreSQLError: No connection to database\n    at DB.connnect"] – all otherwise backend errors
```

I believe it will be useful for backend adapters developers if we got the full life cycle of a few real-world actions example in the Docs. 

Let's discuss is someday

**Comment by ai** [comment]
Nope, the `error` format was changed in recent Back-end Protocol 3.

Now it is `["error", "1560954022858 38:Y7bysd:O0ETfc 1", "PostgreSQLError: No connection to database\n    at DB.connnect"]`

**Comment by ai** [comment]
> I believe it will be useful for backend adapters developers if we got the full life cycle of a few real-world actions example in the Docs.

I can add more examples to https://logux.io/protocols/backend/examples/ What we should cover?
