### ISSUE TITLE
Add common way to send actcions from Django to Logux proxy

### ISSUE THREAD

**Issue by egregors** [logux/django#11]
We need `add` <- `send_back` <- `undo`:

`logux.add` should allow to send any actions to the Logux server from any place in the consumer code.
```
add(action, meta) -> None:
    # just add any action + any meta into logux
    pass
```

`logux.send_back` should call `logux.add` with current aciton (self) + client.id from current acitons meta. Node API ref: 
```
def send_back(prev_action, meta):
    #... 
    meta['clients'] = [self.clientId]
    logux.add(prev_action, meta)
```
@ai what if 'clients' already in consumer meta?

`undo` should send undo actions + collect `undoMeta` Node API ref for `buildMeta`: https://github.com/logux/server/blob/161ac3d21bed848ce88ac64ebef22ed6a93cebed/base-server/index.js#L677 and for `undoAction`: https://github.com/logux/server/blob/161ac3d21bed848ce88ac64ebef22ed6a93cebed/base-server/index.js#L353
```
def undo(meta, reason, extras):
    undo_meta = self.build_undo_meta(meta, reason, extras)
    logux.add(undo_meta.action, ..., ...)
```

**Comment by ai** [comment]
> @ai what if 'clients' already in consumer meta?

Let’s copy Node.js behavior https://github.com/logux/server/blob/master/context/index.js#L18-L20

User’s `client` overrides.
