### ISSUE TITLE
Add ActionCommand helpers

### ISSUE THREAD

**Issue by egregors** [logux/django#12]
- [x] user_id 
- [x] client_id 
- [x] node_id
- [x] time(datatime)
- [x] date_diff (https://github.com/logux/core/blob/master/is-first-older/index.js)
- [x] send_back 
- [x] undo.

rel #11

**Comment by ai** [comment]
Can we overload `<` and `>` for `Meta`? Instead of ugly `is_first_older(meta1, meta2)` we could do `meta1 > meta2`.

**Comment by egregors** [comment]
> Can we overload `<` and `>` for `Meta`? Instead of ugly `is_first_older(meta1, meta2)` we could do `meta1 > meta2`.

Sure, 481efe8ca21fbcd3f04c327802392984d902adc7

**Comment by ai** [comment]
@egregors your `<` and `>` implementation is not full. You forgot a code for `meta1.time === meta2.time` case.

**Comment by egregors** [comment]
Got it. It will be done in at few days. Now I'm focus on the subscriptions support
