### ISSUE TITLE
Move to version 3 of logux protocol

### ISSUE THREAD

**Issue by egregors** [logux/django#14]
I need:
- [x] docs for the new version (changes-like doc will be perfect)
- [x] few examples for back-end
- [x] little guide on how to update my local logux server and client (current version installed according to logux.io docs)

@ai We are dropping ver. 2 support, right?

**Comment by ai** [comment]
Changes: https://logux.io/protocols/backend/versions/

The difference is very small: `"version": 3`, `"secret"` key instead of `"password"` and action ID in `["error", meta.id, stack]` response.
