### ISSUE TITLE
Update test | example frontend app

### ISSUE THREAD

**Issue by egregors** [logux/django#2]
I believe in many cases clear and detailed examples are the best documentation. We need a simple client app with a few typical actions (maybe CRUD for some data model), some cases for playing around subscriptions and error handling.

Please check out `tests/client-logux`. 

I'll add a few CRUD actions from server-side tomorrow.

Dev `.env` for server-logux:
```
LOGUX_BACKEND=http://localhost:8000/logux/
LOGUX_CONTROL_PASSWORD=secret
```

**Comment by ai** [comment]
What do you think about moving examples to the single `logux/examples` repo. Front-end can be re-used for Ruby on Rails and Node.js servers.

**Comment by ai** [comment]
Another question: what app should be used in the example.

1. Counter (number with +1 button). The simplest example.
2. ToDo app. Every framework starts from the ToDo app example nowadays.
3. Chat. The most popular example of real-time system.

**Comment by egregors** [comment]
> Another question: what app should be used in the example.
> 
>     1. Counter (number with +1 button). The simplest example.
> 
>     2. ToDo app. Every framework starts from the ToDo app example nowadays.
> 
>     3. Chat. The most popular example of real-time system.

For now, we need the simplest and quickest way to provide a good example. So I guess ToDo will be enough for now. But for future releases, we definitely should make smth like Real World App. Please check out https://github.com/gothinkster/realworld 

After all, we may submit rails\logux, django\logux, node\logux examples for this `realworld` repo

**Comment by egregors** [comment]
> What do you think about moving examples to the single `logux/examples` repo. Front-end can be re-used for Ruby on Rails and Node.js servers.

It sounds like a good idea in general, however, there is are a few problems:

1. Sometimes examples require specific for particular backend Actions (for example auth through sessions for Django) and common frontend examples should cover all of them.

2. Do you suppose to use submodules? 😨

**Comment by ai** [comment]
> Please check out https://github.com/gothinkster/realworld

Wow, great project. It will be nice to use it as promotion for Logux :smiling_imp:.

> Sometimes examples require specific for particular backend Actions (for example auth through sessions for Django) and common frontend examples should cover all of them.

I have an idea of how to avoid differences. Let’s discuss if on ou further call about Logux Django auth.

> Do you suppose to use submodules? :fearful: 

I hate them too. Why do you think we may need them?

**Comment by egregors** [comment]
Looks like https://github.com/logux/backend-test is exactly I want here.
