### ISSUE TITLE
Add Django examples to docs

### ISSUE THREAD

**Issue by ai** [logux/django#20]
We need to grep all `Node.js` mentions in [`logux/docs`](https://github.com/logux/docs/blob/master/guide/starting/proxy-server.md) and add `Django` example there.

**Comment by egregors** [comment]
- [x] action
- [x] meta
- [x] stat
- [x] recipes\subprotocol
- [x] concepts\subprotocol
- [x] subscription
- [x] node
- [ ] tests
- [ ] auth

**Comment by ai** [comment]
You missed at least this file

https://github.com/logux/docs/blob/master/guide/concepts/node.md

Why do we have all checkbox checked? Your PR has no code snippets fort `action`.

**Comment by egregors** [comment]
> You missed at least this file

My bad. I'll send you one more PR today

> Why do we have all checkbox checked? Your PR has no code snippets fort action.

`action` checkbox means `guide/concepts/action.md` and there is are a lot of changes: https://github.com/egregors/docs/blob/5232b3859601dff4be5bed2e21284d1ccbcd0362/guide/concepts/action.md 

Or you're talking about another part?

**Comment by ai** [comment]
> Or you're talking about another part?

For instance, we have checked checkbox for subprotocols. But PR didn't contain examples for these pages.

**Comment by egregors** [comment]
If I got it correct, we shouldn't add active subprotocols support for backend over Logux Proxy.
> We do not send this data to the back-end, because we have validation that the developer set subprotocol in the server’s code. #28 

So, I don't clearly understand which one code snippets for subprotocols I should add.

Plus, I find than I forget about `tests.md` as well. I wanna add more tests for the package (with consumer-related examples) and add `test` Django snippets.

Sorry about that, for some reason, it looks a bit entangled for me 😞

**Comment by ai** [comment]
> So, I don't clearly understand which one code snippets for subprotocols I should add.

Just grep `Rails` in `logux/docs`. Django snippet will be useful for every place, where we have Rails snippet right now.

For instance, on Subprotocols page we have an example at the end of the page
https://logux.io/guide/concepts/subprotocol/

There are also many places with Rails examples in the docs.

**Comment by egregors** [comment]
rel https://github.com/logux/docs/pull/68

**Comment by egregors** [comment]
Looks done
