### ISSUE TITLE
Add more autotools

### ISSUE THREAD

**Issue by ai** [logux/django#22]
- [x] `.editorconfig`
- [x] Linter
- [x] Formatter?
- [x] Travis CI for tests and linter

**Comment by egregors** [comment]
@ai I have added Travis CI config, but I can't add the project to Travis side because of I haven't Logux Organisation permissions. Could you please check it out?

**Comment by ai** [comment]
@egregors done https://travis-ci.org/github/logux/django

**Comment by egregors** [comment]
Can't check what's wrong with `.travis.yml` because Trasiv does not work properly now: https://github.com/travis-ci/travis-ci/issues/7443 😞

**Comment by egregors** [comment]
You know, I’ll just make it by github actions for now

**Comment by ai** [comment]
Yeap, let’s go to GitHub Actions

**Comment by egregors** [comment]
GitHub actions CI is ready. And Travis as well.
