### ISSUE TITLE
Add CHANGES.md to track changes from version to version.

### ISSUE THREAD

**Issue by egregors** [logux/django#26]

**Comment by ai** [comment]
:+1: ChangeLog is very important

**Comment by while0pass** [comment]
Why not follow the ["Keep a Changelog" spec](https://keepachangelog.com/)?

**Comment by ai** [comment]
@while0pass what is the difference with current file?

**Comment by while0pass** [comment]
@ai It's not that much at first glance. I find their systemizing principles to be helpful (`Added`, `Changed`, `Deprecated`, `Removed`, `Fixed`, `Security` groups, and `Unreleased` section). Perhaps, logux-django is at such an early stage, that it doesn't much matter so far, though.

**Comment by ai** [comment]
I think having a group for 1-2 items is not useful. But I agree that sections are useful when we have >10 items.
