### ISSUE TITLE
Add sphinx auto doc's

### ISSUE THREAD

**Issue by egregors** [logux/django#27]
- [x] sphinx integration
- [x] doc strings -> ?
  - [x] xml
  - [x] html 

rel #23

**Comment by ai** [comment]
Markdown will be enough. I can parse Markdown instead of JSON if sphinx doesn’t have JSON output.

Does it support types?

**Comment by egregors** [comment]
Give me a little time to play around with Sphinx. I'll show you an example of autogen doc's when the Sphinx integration will be ready

**Comment by egregors** [comment]
@ai so... Sphinx is not supported markdown output format from the box :/ However, they support many other formats: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#options Please check it out, which one is the most comfortable for you for parsing.

How to run doc's generation:
* Install Sphinx: https://www.sphinx-doc.org/en/master/usage/installation.html 
* go to the project folder and run `make docs` (it makes default HTML docs, which will be available in `./docs/_build/html/index.html`

Otherwise, you make try to play with doc's builder formats, just make `make help` in the `./docs` folder. 

Right now all of this does not look super pretty, but I believe it's good enough for the start.

![2020-04-23_15-13-17](https://user-images.githubusercontent.com/2153895/80061572-fe74f600-8574-11ea-9dff-6153f0a886e6.png)
![2020-04-23_15-12-58](https://user-images.githubusercontent.com/2153895/80061580-02a11380-8575-11ea-92c2-8996d561abd1.png)


ref: https://github.com/logux/django/commit/4b1043a08db85e5cf50872a97ff5a609ac2cf548

**Comment by ai** [comment]
The XML format can be then converted. Hope it is well structured.

**Comment by ai** [comment]
I lost myself in Pathologic 2 game. Can we move to this issue for now? https://github.com/logux/django/issues/20

**Comment by egregors** [comment]
> I lost myself in Pathologic 2 game. Can we move to this issue for now? #20

Is it good? I saw a few streams on the Twitch, and it looked very ambiance 🎮 🎮 🎮 

Sure. Already in progress. I have slowed down a little bit because of the number of other tasks last week.

**Comment by egregors** [comment]
@ai I just reproduced an error from logux.io repo. So, I gonna fix my Makefile for docs gen first  🏭 🏭 🏭 

Please check the latest master version, I have updated make docs. Now it works without errors, at least locally.

**Comment by egregors** [comment]
@ai, please check the latest ~~master~~ version, I have updated `make docs`. Now it works without errors, at least locally.

**Comment by ai** [comment]
Yeap, it was fixed.

But you need to help me in enabling XML output format. [Config docs](https://www.sphinx-doc.org/en/master/usage/configuration.html) and Google were not helpful.

**Comment by egregors** [comment]
Done, `make docs` now makes xml

**Comment by egregors** [comment]
Looks like XML is good enough
