### ISSUE TITLE
Default way to authentication

### ISSUE THREAD

**Issue by egregors** [logux/django#3]
Django does not support JWT from the box. The default way to auth is sessions in the cookies. 
We need to decide: add [Django REST Framework](https://www.django-rest-framework.org/) support which has common and most popular JWT implementation, or try to figure out how to use sessions for logux auth.

**Comment by ai** [comment]
Of course, Logux can’t use cookies. But we can read session ID from the cookie and use it as a token.

Possible problems of using session ID:

1. Can we read the Django session cookie by JS? There is a popular (and very useful) idea to set `HttpOnly` flag to session cookie and make it impossible to read the cookie from JS.
2. Using a cookie is good when HTML is generated by Django (so Django will set session ID when the app will be loaded). By right now it is a more popular way to isolate front-end and back-end into separated apps. In this case, we will have an independent Docker image with nginx, which will load HTML to the client. So we will need some other way to get session ID.
3. Session ID authentification is slower. We need to go into a database to load user data.

I think JWT is a simpler and more universal way of token validation. But I think it will be better to discuss authentification in Zoom.

Do we have a JWT library from Django?

**Comment by egregors** [comment]
For now, we decided that consumer should provide auth functions (`LOGUX_AUTH_FUNC` setting) according to the auth method that they using generally in the App
