### ISSUE TITLE
Add tests for "backend-test" Logux App

### ISSUE THREAD

**Issue by egregors** [logux/django#40]
Front test app: https://github.com/logux/backend-test 

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] 13
- [x] 14
- [x] 15
- [x] 16
- [x] 17
- [x] 18
- [x] 19
- [x] 20

**Comment by ai** [comment]
`@logux/backend-test` 4.0 was released

**Comment by egregors** [comment]
ref https://github.com/logux/backend-test/issues/3

**Comment by egregors** [comment]
ref https://github.com/logux/backend-test/issues/4

**Comment by egregors** [comment]
Just 19th and 20th tests are left

**Comment by egregors** [comment]
All looks done if @ai accept this PR: https://github.com/logux/backend-test/pull/10

**Comment by egregors** [comment]
Done in release 2.0
