### ISSUE TITLE
Consider adding `django-stubs`

### ISSUE THREAD

**Issue by sobolevn** [logux/django#45]
Hi! Thanks a lot for your awesome project.

Looks like you are using `django` with lots of type annotations and enabled `mypy`.
I suggest to add `django-stubs` support, this is a project that provides type annotations and optional plugin for `mypy` to work correctly with `django`.

See https://github.com/typeddjango/django-stubs

**Comment by egregors** [comment]
👍 Thanks, I'll check it soon. 
Right now 2.0 release is a priority task. 
After all, feel free to PR with stubs support :)
