### ISSUE TITLE
TypeScript to Django types

### ISSUE THREAD

**Issue by ai** [logux/django#48]
I have a dream of re-using types between front-end and Logux Django.

In front-end we have types like:

```ts
type AddUserAction = {
  type: 'users/add',
  payload: {
    id: string,
    age: number,
    name: string
  }
}
```

For actions, we can use only simple JSON-compatible types (array, object, string, number, boolean, `null`).

Do we have a way to convert it to Django types? If needed we can force users to write TypeScript types in a special format

/cc @sobolevn

**Comment by sobolevn** [comment]
I am pretty sure that there's no official way to do that.
However, there are several options I know:
- Using https://pypi.org/project/py-ts-interfaces/ you can generate TS interfaces and check their compatibilty with existing ones
- It is possible to use some other type-enforcement format like `ProtoBuf`, `JsonSchema`, `Pact`. There are ways to convert to these formats from both TypeScript and Python. But it will require some work on both ends

**Comment by ai** [comment]
`py-ts-interfaces` looks exactly what I want. Thanks.

**Comment by ai** [comment]
Not interesting for a while
