### ISSUE TITLE
Action callback details

### ISSUE THREAD

**Issue by egregors** [logux/django#5]
For now `LoguxCommand` inheritor may implement some of 3 methods: resend, access and process. 

According to Node API `access` is the only required method. Is it correct? 

And I saw `finally` callback in Node API docs: https://logux.io/node-api/#actioncallbacks . Is it actual info? Should `LoguxCommand` implement this method? 

Next, if all right we may get `LoguxCommand` instance with 1 to 3(4)  implemented methods.
One more time, what exactly order to apply each of them? 

```
resend -> access -> process
```
Right?

**Comment by ai** [comment]
> According to Node API access is the only required method. Is it correct?

Yeap

> And I saw finally callback in Node API docs: https://logux.io/node-api/#actioncallbacks . Is it actual info? Should LoguxCommand implement this method?

It is not required, but I found it very useful in some rare use cases.

I think it will be nice to have it in Django API as well.

> Next, if all right we may get LoguxCommand instance with 1 to 3(4) implemented methods.

Of course, it will be nice to keep the same object for all methods call.

```python
command = LoguxActionCommand()
try:
  command.resend()
  if command.access():
    command.process()
except (Error):
  send_error()
finally:
  command.finally()
```

In this case, steps could share variables with each other.

> resend -> access -> process

Yeap
