### ISSUE TITLE
Bruteforce protection

### ISSUE THREAD

**Issue by ai** [logux/django#6]
Everyone who will send commands to `/logux` will have full access to the server, because of web server trust to Logux server data. This is why it is very important to protect this URL.

The best solution is to add a firewall and block and request to `/logux` outside of the network. But I am sure that most of the users will forget it.

As an extra protection, we require the Logux server and web server to share the same `password` and we use it in requests.

But it is impossible to brute-force this password. So we need to have protection against it.

**Comment by egregors** [comment]
Test example:
```js
// Must be always the last test
it('Protects from brute-force', async ({ backend, controlSecret }) => {
  let secrets = []
  for (let i = 0; i < 10; i++) {
    secrets.push(controlSecret + i.toString())
  }
  secrets.push(controlSecret)
  let answers = await Promise.all(
    secrets.map(secret =>
      send(backend, {
        version: 4,
        secret,
        commands: []
      })
    )
  )
  check(429, 'Too many wrong secret attempts', answers[answers.length - 1])
})
```

**Comment by egregors** [comment]
Node implementation refs: 
* helper: https://github.com/logux/server/blob/master/server-client/index.js#L142-L147 
* struct: https://github.com/logux/server/blob/f1216f47eaeda258d2091f6aade95b35b918bd1b/base-server/index.js#L711-L714
* timer: https://github.com/logux/server/blob/f1216f47eaeda258d2091f6aade95b35b918bd1b/base-server/index.js#L700-L709

**Comment by egregors** [comment]
```js
https://github.com/logux/server/blob/master/bind-control-server/index.js#L67-L71
```
