### ISSUE TITLE
How backend server should handle Logux System Actions? 

### ISSUE THREAD

**Issue by egregors** [logux/django#9]
Is it all Logux System Actions?
```
logux/processed
logux/undo
logux/subscribe
logux/unsubscribe
```

How exactly backend should handle these actions?

Is the default action dispatcher should include system actions handlers or it should be consumer's handlers?

**Comment by ai** [comment]
Yeap, this is a full list of `logux/*` actions.

Back-end needs to handle only `logux/subscribe`. All other actions will not be sent to back-end.
